version: "3.7"
services:

  local.dev:
    container_name: local.dev
    image: katoni/local.dev:latest
    build: .
    ports:
      - "${DOCKER_BIND_IP:-0.0.0.0}:80:80"
      - "${DOCKER_BIND_IP:-0.0.0.0}:443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - secrets:/run/secrets
    restart: unless-stopped

  whoami:
    image: containous/whoami
    labels:
      - "local.dev.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
      - "traefik.http.routers.whoami.middlewares=redirect-http-to-https@file" # optional

volumes:
  secrets:

networks:
  default:
    name: local.dev
    external: false
